### ISSUE TITLE
todo: news.html

### ISSUE THREAD

**Issue by H4ppy-04** [vitunix/vitunix.github.io#1]
News page currently missing in navbar

**Comment by heapbytes** [comment]
Hello Joshua, the website is still under development, we are busy with openbox WM development. 
Will update it soon, stay tuned :star2: 
If there are no further doubts, you can close this issue ......... and feel free open other issue if you have any doubts  :+1:

**Comment by H4ppy-04** [comment]
For sure
Sorry, I'm a bit out of it today. Normally I just create issues on everything I see even tho that's not the way your meant to do it haha so I'm sorry if this came as a bit of a weird notification.

Love the work yall are doing, wishing well for future development
